name: AllMusic
main: Color_yr.AllMusic.AllMusicBukkit
author: Color_yr
version: ${version}
loadbefore: [vexview, VexView, PlaceholderAPI]
softdepend: [vexview, VexView, PlaceholderAPI]

commands:
  music:
    description: ALLMusic
    usage: ยง4[ALLMusic]ยง6/music help
