name: ALLMusic
main: Color_yr.ALLMusic.ALLMusicBukkit
author: Color_yr
version: 1.8.0
loadbefore:
  - vexview
softdepend:
  - vexview

commands:
  music:
    description: ALLMusic的主要指令
    usage: §4[ALLMusic]§6/music help来查看帮助
