name: AllMusic
main: coloryr.allmusic.AllMusicBukkit
author: Color_yr
version: 2.16.5
loadbefore: [PlaceholderAPI, Vault, Essentials, CMI]
api-version: 1.13

commands:
  music:
    description: AllMusic
    usage: ยง4[AllMusic]ยง6/music help
