name: AllMusic
main: Color_yr.AllMusic.AllMusicBukkit
author: Color_yr
version: 2.11.0
loadbefore: [PlaceholderAPI, Vault, Essentials, CMI]
softdepend: [PlaceholderAPI, Vault]

commands:
  music:
    description: AllMusic
    usage: ยง4[AllMusic]ยง6/music help
