name: AllMusic3
main: com.coloryr.allmusic.server.AllMusicBukkit
author: Color_yr
version: 3.1.0
softdepend: [PlaceholderAPI, Vault, Essentials, CMI]
api-version: 1.13

commands:
  music:
    description: AllMusic3
    usage: ยง4[AllMusic3]ยง6/music help
