name: AllMusic3
main: com.coloryr.allmusic.server.AllMusicFolia
author: Color_yr
version: 3.0.0
folia-supported: true
softdepend: [PlaceholderAPI, Vault, Essentials, CMI]
api-version: 1.19

commands:
  music:
    description: AllMusic3
    usage: ยง4[AllMusic3]ยง6/music help
