name: AllMusic
main: coloryr.allmusic.AllMusicFolia
author: Color_yr
version: 2.19.4
folia-supported: true
softdepend: [PlaceholderAPI, Vault, Essentials, CMI]
api-version: 1.19

commands:
  music:
    description: AllMusic
    usage: ยง4[AllMusic]ยง6/music help
